blog/urls.py
from django.conf.urls import url

from . import views
from . import feeds
from .models import Post

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.ArchiveView.as_view(model=Post, date_field='pub_date'), name='index'),
    url(r'^(?P<pk>[0-9]+)-(?P<slug>[0-9|_\-|a-z]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^rss', feeds.LatestPostsFeed())
]

dj_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.views import IndexView
from blog.views import TagsView
from blog.views import BlogSitemap

sitemaps = {
    "blog": BlogSitemap
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^posts/', include('blog.urls')),
    url(r'^tags/([\w-]+)/$', TagsView.as_view(), name='tags'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^$', IndexView.as_view(), name='home')

]

blog/models.py
from __future__ import unicode_literals
from django.utils import timezone

from django.db import models
from django.utils.text import slugify

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.name

class Post(models.Model):

    def prev_post_choices(pub_date):
        return {
            'pub_date__lte': pub_date
        }

    title = models.CharField(max_length=255)
    body = models.TextField()
    summary = models.TextField(null=True, blank=True)
    slug = models.SlugField(max_length=255)
    pub_date = models.DateTimeField('Published at')
    published = models.BooleanField()
    tags = models.ManyToManyField(Tag)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    previous = models.OneToOneField('self',
                                 related_name='previous_post',
                                 blank=True,
                                 null=True,
                                 on_delete=None)

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('blog:detail', [self.id, self.slug])

    class Meta:
        ordering = ['-pub_date']

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from .models import Post, Tag
from django.contrib.sitemaps import Sitemap


class IndexView(generic.ListView):
    def get_queryset(self):
        """Return the last five published questions."""
        return Post.objects.filter(
            published=True
        ).order_by('-pub_date').prefetch_related('tags')[:4]


class ArchiveView(generic.ArchiveIndexView):
    model = Post
    template_name = 'blog/archive_list.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.filter(
            published=True
        ).order_by('-pub_date').prefetch_related('tags')


class DetailView(generic.DetailView):
    model = Post

    def dispatch(self, request, *args, **kwargs):
        object = get_object_or_404(Post, pk=self.kwargs['pk'])
        if object.slug != self.kwargs['slug']:
            return redirect(object, permanent=True)
        return super(DetailView, self).dispatch(request, *args, **kwargs)


class TagsView(generic.ListView):
    template_name = 'blog/archive_list.html'

    def get_queryset(self):
        self.term = get_object_or_404(Tag, slug=self.args[0])
        return Post.objects.filter(
            tags=self.term
        ).filter(
            published=True
        ).order_by('-pub_date')


class BlogSitemap(Sitemap):
    changefreq = "monthly"
    priority = 0.5

    def items(self):
        return Post.objects.filter(published=True).order_by('-pub_date')

    def lastmod(self, obj):
        return obj.updated

blog/templates/blog/archive_list.html
{% extends "base.html" %}
{% block content %}
{% include "blog/listing.html" %}
{% endblock %}

blog/templates/blog/listing.html
{% load markdownify %}
<div class="posts">

    {% for post in post_list %}
        <section class="post">
            <header class="post-header">

                <h2 class="post-title">
                    <a href="{% url "blog:detail" post.id post.slug %}">{{ post.title }}</a>
                </h2>

                <p class="post-meta">
                    <time>{{ post.pub_date }}</time> in {% for tag in post.tags.all %}
                    <a href="{% url "tags" tag.slug %}" class="post-category post-category-{{ tag.id }}">{{ tag.name }}</a>
                    {% endfor %}
                </p>
            </header>

            <div class="post-description">
                <p>
                    {{ post.body | markdown | safe | truncatewords_html:60  }}
                </p>
            </div>
        </section>
    {% endfor %}

</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% load tags %}

{% block content %}
    <section class="post">
        {% include 'blog/prev_next_buttons.html' %}
        <header class="post-header">
            <h2 class="post-title">{{ post.title }}</h2>
            <time>{{ post.pub_date }}</time>
            in {% for tag in post.tags.all %}
            <a href="{% url "tags" tag.slug %}" class="post-category post-category-{{ tag.id }}">{{ tag.name }}</a>
        {% endfor %}
        </header>

        <div class="post-description">
            {{ post.body | markdown | safe }}

            <div id="related">
                {% get_related post as related %}
                {% if related %}
                <h3>(semi)Related</h3>
                <ul>
                    {% for item in related %}
                    <li><a href="{% url "blog:detail" item.id item.slug %}">{{ item.title }}</a></li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>

            {% if user.is_authenticated %}
            <div class="edit-link">
                <a class="pure-button" href="{% url "admin:blog_post_change" post.id %}">Edit</a>
            </div>
        {% endif %}
            {% include 'blog/prev_next_buttons.html' %}
            <div id="disqus_thread"></div>
            <script>
                (function () { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = '//ignoredbydinosaurs.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                })();
            </script>
            <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments
                powered by Disqus.</a></noscript>
        </div>
    </section>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
    <!-- A wrapper for all the blog posts -->
    <div class="posts">
        <h1 class="content-subhead">About this</h1>

        <!-- A single blog post -->
        <section class="post">
            <header class="post-header">

                <h2 class="post-title">Hello.</h2>

            </header>

            <div class="post-description">
                <p>
                    This blog began life as a chronicle of my life inside a touring band with a music/business idea. The
                    early days were me writing about letting go of an old dream so that I could have a new one.
                    Then it sort of turned into an autobiography
                    of the last 8 or so years of my life - moving from the music business into the tech
                    business, fatherhood, life and all that.
                </p>
                <p>
                    For the last 8 years I've worked with, thought about, and written about a variety of web
                    technologies - Drupal, Rails,
                    Linux, AWS.
                    <a href="https://www.linkedin.com/in/johnnygrubb">My LinkedIn resume is here.</a> I still think and
                    occasionally write about the music business and other personal things but I think
                    it's about to turn into a blog about learning Python for web and doing "data stuff".
                </p>
                <p>
                    So welcome and please have a look around.
                </p>
                <p><em>- Grubb, March 2016</em></p>
            </div>
        </section>
    </div>

    <h1 class="content-subhead">Recent Posts</h1>

    {% include 'blog/listing.html' %}

    <a class="pure-button pure-button-primary" href="{% url "blog:index" %}">The blog archive -></a>
{% endblock %}

blog/templates/blog/prev_next_buttons.html
{% if post.previous %}
    <small>
        <a class="pure-button pure-button-primary"
           href="{% url "blog:detail" post.previous.id post.previous.slug %}">&larr;
            previous: {{ post.previous.title }}</a>
    </small>
{% endif %}
{% with next=post.previous_post %}
    {% if next %}
        <small>
            <a class="pure-button pure-button-primary"
               href="{% url "blog:detail" next.id next.slug %}">next: {{ next.title }} &rarr;</a>
        </small>
    {% endif %}
{% endwith %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% load markdownify %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{ post.body | truncatechars_html:260 | striptags | safe }}">
    <link rel="alternate" type="application/rss+xml" title="IBD RSS" href="/posts/rss.xml"/>
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    <link rel="shortcut icon" href="/static/favicon.png">

    <title>Ignored By Dinosaurs{% if post.title %} | {{ post.title }}{% endif %}</title>
    <link rel="stylesheet" href="{% static 'css/pure-min.css' %}">
    <!--[if lte IE 8]>

    <link rel="stylesheet" href="{% static 'css/grids-responsive-old-ie-min.css' %}">

<![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="{% static 'css/grids-responsive-min.css' %}">
    <!--<![endif]-->
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="{% static  'css/layouts/blog-old-ie.css' %}">
    <![endif]-->
    <!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="{% static 'css/layouts/blog.css' %}">
    <!--<![endif]-->
    <meta name="google-site-verification" content="ZW3GBpFJ0aC-Xr6n__YokO1Yy_Mba3osaM0bOfGhGVI"/>
    <meta property="fb:pages" content="1024603974292271" />
</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title">
                <a href="/">Ignored By Dinosaurs</a>
            </h1>
            <h2 class="brand-tagline">A blog about hacking, but really more in a golfish sense.</h2>

            {% if user.is_authenticated %}
                <nav class="nav">
                    <ul class="nav-list">
                        <li class="nav-item">
                            <a class="pure-button" href="{% url "admin:index" %}">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="pure-button" href="{% url "admin:blog_post_add" %}">New Post</a>
                        </li>
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal">
                    <ul>
                        {#                        <li class="pure-menu-item"><a href="http://purecss.io/" class="pure-menu-link">About</a></li>#}
                        <li class="pure-menu-item"><a href="http://twitter.com/johnnygrubb/" class="pure-menu-link">Twitter</a>
                        </li>
                        <li class="pure-menu-item"><a href="http://github.com/jgrubb/"
                                                      class="pure-menu-link">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-8646459-1', 'auto');
    ga('send', 'pageview');

</script>
</body>
</html>